version: '3.8'

services:
  server:
    build: 
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - MONGODB_URI=mongodb://admin:secret@mongodb:27017/xcaro?authSource=admin
      - DB_NAME=xcaro
      - PORT=8080
      - JWT_SECRET=xcaro-jwt-secret-key-2024
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=secret
      - MONGO_INITDB_DATABASE=xcaro
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: 